version: '3'

services:
  app:
    build: .
    ports:
      - 4000:3000
    volumes:
      - .:/home/node/app
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest